name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.14.1

jobs:
  build-test:
    name: build & test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          cache-key: ${{ matrix.os }}-${{ env.ZIG_VERSION }}

      - name: zig build (Debug)
        run: zig build

      # - name: zig build test
      #   run: zig build test

      - name: zig build (Release Safe)
        run: zig build --release safe
