name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-lint
  cancel-in-progress: true

env:
  ZIG_VERSION: 0.14.1

jobs:
  fmt:
    name: zig fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Check formatting
        run: zig fmt --check .
